### ISSUE TITLE
Nuget publishing

### ISSUE THREAD

**Issue by fahadabdulaziz** [cgtheodorou/boilerpipe.net-core#1]
Hello, 
Thank you for porting the library to .net core.
Don't you think it good to publish it on nuget ?

Thanks

**Comment by cgtheodorou** [comment]
Hi!

You're right, I did actually consider packaging it up but was too busy trying to finish what I was working on at the time.

I'll go ahead and publish it on nuget today, thanks for the suggestion!

**Comment by fahadabdulaziz** [comment]
Thank you, 
please if you may, when publish it alert me.

Thank you 👍

**Comment by cgtheodorou** [comment]
Hi again!

Sorry for the delay, the project is available now as a package on NuGet. You can find it here https://www.nuget.org/packages/Boilerpipe.Net.Core or via the package manager in visual studio.

**Comment by fahadabdulaziz** [comment]
Hi
Thank you for, But there is a little problem
The package is targeting .NET Core only, why not target .NET Standard instead ?
I tried installing it but I got this error:
`Package Boilerpipe.Net.Core 1.0.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Boilerpipe.Net.Core 1.0.0 supports: netcoreapp1.1 (.NETCoreApp,Version=v1.1)`

Thanks :-)

**Comment by cgtheodorou** [comment]
Oh right, my bad! 

I've updated this as well as the Sax.Net.Core package which is a dependency to target at least .NET Standard 1.3 so you should be able to install it shortly once its done indexing!

**Comment by fahadabdulaziz** [comment]
Thank you, just installed 👍
