### ISSUE TITLE
Article extractor underperforming 

### ISSUE THREAD

**Issue by Gal258** [cgtheodorou/boilerpipe.net-core#3]
I am trying to use the nuget package and the Article extractor is underperforming compared to the web api(https://boilerpipe-web.appspot.com/) try these examples and see for yourself (http://www.techradar.com/news/phone-and-communications/mobile-phones/iphone-8-1329124, https://www.macrumors.com/roundup/iphone-8/ (news articles btw)). and when I say underperforme I mean only gets 20% of the text. I would use the web api but i dont have a token and it has a hard limit of 1 req per second so thats not an option, is there any chance you can help me resolve this quickly?

**Comment by cgtheodorou** [comment]
Hi, thanks for the feedback I'm looking into this right now. I'll let you know as soon as I have something.

**Comment by Gal258** [comment]
thanks for the quick response

**Comment by cgtheodorou** [comment]
Hi, looks like the .NET 4.5 lib suffers from the same issue. Depending on your use case, the DefaultExtractor could help to sort of work around the issue but it does parse some extra stuff (image titles, comments).

I need a bit more time to look into why its skipping some of the nodes.

**Comment by Gal258** [comment]
any idea why the web api is performing well?

**Comment by Gal258** [comment]
also i tried some other articles with the article extractor and none of them get exctracted correctly, why is this happening? am i using it wrong(calling CommonExtractor.ArticleExtractor.GetText(html))casue this lib is supposed to be one of the better text exctracting libs out there, can you show me an example where it works correctly?

**Comment by phillijw** [comment]
Yeah, this just flat out doesn't get any text for me when using it to parse RSS feed item descriptions

**Comment by geaninmihai** [comment]
Any updates here?

**Comment by geaninmihai** [comment]
> Any updates here?

Sorry, It was my mistake.
I passed the URL, not the entire html body content.
Now, using the right parameters, method (and implicit the library) works as expected for me.
